# c3 Community Partners DAO funding links
github: [] # (optional, if you enable GitHub Sponsors later)
patreon: [] # (optional)
open_collective: [] # (optional)

# Direct support links
custom: 
  - "https://paragraph.xyz/@c3codex"
  - "https://zora.co/c3codex"
  - "https://etherscan.io/address/0xee9C3372A7EB84e84eD1B6d17daAcdD39686b59C"
